### ISSUE TITLE
dq_init step not finding file

### ISSUE THREAD

**Issue by shanosborne** [STScI-MESA/calibration-pipeline-testing-tool#3]
For the dq_init step, when I use an input file called (for example) filename_uncal_001.fits, a new file is created called filename_uncal_001_dqinitstep.fits, but the test report shows that the code is looking for filename_001_dqinitstep.fits and is thus failing to read in this file. Is this something to do with how I'm naming my files?

**Comment by mattjhill** [comment]
This was an issue with me relying on automatically generated filenames. Fixed in #7
